### ISSUE TITLE
Weighted Randomization

### ISSUE THREAD

**Issue by Alce002** [Alce002/PyMENACE#1]
#### Weights
- [x] Weights between 0 and 1
- [ ] Unlimited positive and negative
#### Randomization function
Find possibilities

**Comment by EmilManelius** [comment]
Note to self: f(x) were x is nudge (constant for win loss) and f(x) change to weight W

**Comment by Alce002** [comment]
find function g(n) giving proper f(x) for n possible moves in given position

**Comment by EmilManelius** [comment]
Method for determining new intervals after weight adjustment: Calculate new values for x0 to xn, insert new intervals in order 1 - x0....xn - 0
